name = "cloudflare-short-link"
main = "src/index.ts"
compatibility_date = "2024-04-03"
assets = { directory = "./public" }

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAACpO5kHNRhLAhQOH"

[[routes]]
pattern = "punchy.me"
custom_domain = true

[[kv_namespaces]]
binding = "SHORT_LINKS"
id = "e5c2bbb9a5f04d409e42350fc025ea2d"

[ai]
binding = "AI"
remote = true

[[d1_databases]]
binding = "THOR_STORAGE"
database_name = "THOR_STORAGE"
database_id = "your-d1-id-placeholder"

[[vectorize]]
binding = "THOR_MEMORY"
index_name = "THOR_MEMORY"

[browser]
binding = "BROWSER"
